title: LuaTS
description: A TypeScript library for parsing, formatting, and providing type interfaces for Lua and Luau code
url: https://codemeapixel.github.io/luats
repository: codemeapixel/luats
remote_theme: just-the-docs/just-the-docs

# Enable plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-redirect-from

# Color scheme settings
color_scheme: dark-code
color_scheme_toggle: true
preferred_color_scheme: dark

# Available color schemes for the theme toggle
color_schemes:
  - name: mellow
    label: Mellow
  - name: luau
    label: Luau
  - name: dark-code
    label: Dark Code

# Enable or disable the site search
search_enabled: true

# Heading anchor links
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024-2025 CodeMeAPixel. Distributed under an <a href=\"https://github.com/codemeapixel/luats/blob/main/LICENSE\">MIT license.</a>"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/logo.png"

# Aux links for the upper right navigation
aux_links:
  "Luats on GitHub":
    - "//github.com/codemeapixel/luats"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  important:
    title: Important
    color: red
  tip:
    title: Tip
    color: green

# For Mermaid diagrams
mermaid:
  version: "9.1.3"

# Optimize for better accessibility
a11y:
  skip_to_content: true
  nav_buttons: true

exclude:
    - README.md
    - node_modules/
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/